Refactor/libraries
provokateurin/nextcloud-neon pull request #436
Opened 2023-07-01 12:22 UTC by provokateurin

Closes https://github.com/provokateurin/nextcloud-neon/issues/433

2023-07-01 13:12 UTC, Leptopoda requested changes
Some random thoughts. They may not all make sense.

- I think that all libs should add the `library` directive with a small little doc comment.
- All private stuff should be annotated with `@internal` so we don't accidentally export it (directly or indirectly). This might be useful for internal widgets and the blocs.

2023-07-01 13:12 UTC, Leptopoda commented on packages/neon/neon/lib/utils.dart
> +export 'package:neon/src/utils/app_implementation.dart';
I never liked this being a util.

It should rather be a model or interface but I don't know how much it makes sense :(

2023-07-01 13:12 UTC, Leptopoda commented on packages/neon/neon/lib/blocs.dart
Should this also export bloc?
How much does it make sense to have them separated once the AccountsBloc isn't exported anymore?

2023-07-01 13:12 UTC, Leptopoda commented on packages/neon/neon/lib/utils.dart
> +export 'package:neon/src/utils/storage.dart';
moved to settings?

2023-07-01 13:17 UTC, Leptopoda commented
I just noticed that neon is directly exposing types defined in nextcloud.

If dynamite or the specs would change some naming this would not only result in breaking changes to nextcloud but also in neon.
We should abstract away all nextcloud types that we expose into their own typedefs. Internally we can still use the normal types.

2023-07-01 19:27 UTC, provokateurin commented on packages/neon/neon/lib/interfaces.dart
> +export 'package:neon/src/interfaces/notifications.dart';
We could do that, but for me models is something to model concrete data and not to model some abstract interface that gets implemented elsewhere

2023-07-01 19:29 UTC, provokateurin commented
I agree with you on most points. Moving to models makes sense :+1:

2023-07-02 08:43 UTC, provokateurin commented on packages/neon/neon/lib/blocs.dart
Yeah let's expose them together as blocs.

2023-07-02 09:12 UTC, provokateurin commented
@Leptopoda  Should we also export file_icons and nextcloud through the neon package?

2023-07-02 09:41 UTC, Leptopoda reviewed
I'd really like to have internal annotations on things that we don't (want to ever) export.
[0001-neon-add-internal-annotations.patch.txt](https://github.com/provokateurin/nextcloud-neon/files/11929134/0001-neon-add-internal-annotations.patch.txt)

2023-07-02 09:41 UTC, Leptopoda commented on packages/neon/neon/lib/src/widgets/drawer_destination.dart
should be exported as it's gonna be needed for the adaptive layout.

Or should I just expoprt it then?

2023-07-02 09:41 UTC, Leptopoda commented on packages/neon/neon/lib/src/utils/stream_listenable.dart
Could be exported (doesn't need to)

2023-07-02 09:41 UTC, Leptopoda commented on packages/neon/neon/lib/settings.dart
Could we structure the settings folder in a way similar to all other packages?

/settings
|-> widgets
|-> models
| -> ...

it's currently all over the place

2023-07-02 09:43 UTC, provokateurin commented on packages/neon/neon/lib/src/widgets/drawer_destination.dart
Yeah just export it when needed. I only added exports for things that are used outside the neon package right now

2023-07-02 09:44 UTC, provokateurin commented on packages/neon/neon/lib/src/utils/stream_listenable.dart
Just export it when you need it

2023-07-02 09:45 UTC, Leptopoda commented
> @Leptopoda Should we also export file_icons and nextcloud through the neon package?

Yeah this would probably make thing easier for devs.
But I don't know where :(
The neon library is currently not needed for apps (like files, notes ...) and only needed the `app` itself.
We'd need to come up with a better place for this.

2023-07-02 09:45 UTC, provokateurin commented
> I'd really like to have internal annotations on things that we don't (want to ever) export.

I looked at your patch and I don't agree with all of it. For example `NeonUserAvatar` will be needed for Talk as we want to display the user avatars there.

2023-07-02 09:46 UTC, provokateurin commented
>  We'd need to come up with a better place for this.

Ok let's keep this in mind and do it at some later point

2023-07-02 09:47 UTC, Leptopoda commented
> I looked at your patch and I don't agree with all of it. For example NeonUserAvatar will be needed for Talk as we want to display the user avatars there.

I added it to every major internal class. I didn't know you are currently only exporting used things.
I'm fine with not everything having them but things like the theme should probably have them.

2023-07-02 10:25 UTC, Leptopoda approved these changes
LGTM

2023-07-02 10:55 UTC, merged