fix(dynamite): add serializers of parameter types
provokateurin/nextcloud-neon pull request #501
Opened 2023-07-17 18:58 UTC by Leptopoda

fixes the issue observed in #465

2023-07-22 06:36 UTC, Leptopoda commented
In theory we could now remove the serializer code generated by built_value as we already register all serializers.
This would recude duplicate initialization of them.

2023-07-29 04:54 UTC, provokateurin commented
Deduplicating sounds good

2023-07-29 04:54 UTC, provokateurin approved these changes

2023-07-29 06:17 UTC, provokateurin requested changes
You need to regenerate the nextcloud package

2023-07-30 15:28 UTC, provokateurin approved these changes

2023-07-30 21:39 UTC, merged